ImageEmotionalStatistics/Models/Shared/UserRaiting.cs
using System.Collections.Generic;

namespace ImageEmotionalStatistics.Models.Shared
{
    public class UserRaiting
    {
        public List<UserInfo> Users { get; set; }
        public UserInfo AuthorInfo { get; set; }
    }

    public class UserInfo
    {
        public string Name { get; set; }
        public string ComputerName { get; set; }
        public int CountAnswers { get; set; }
    }
}

ImageEmotionalStatistics/Controllers/BaseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ImageEmotionalStatistics.DataLayer.DataModels;
using ImageEmotionalStatistics.Models.Shared;

namespace ImageEmotionalStatistics.Controllers
{
    public class BaseController : Controller
    {
        protected readonly ImageEmotionalEntities ImageEntities = new ImageEmotionalEntities();
        private readonly object _lockObj = new object();

        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            ViewData["Users"] = GetUsersRaiting();
        }

        /// <summary>
        /// Круто было бы использовать регистрацию и идентифицировать пользователя по логину\паролю, но вряд ли кто-то будет регистрироваться
        /// Также можно сохранять какие-то данные на клиенте в кэш, и потом идентифицировать по ним. Но они могут устаревать и т.п.
        /// </summary>
        protected string GetComputerName()
        {
            return Request.ServerVariables["REMOTE_ADDR"];
        }

        private UserRaiting GetUsersRaiting()
        {
            var userRaiting = new UserRaiting();
            var userInfoes = ImageEntities.UserAnswers.Select(item => new UserInfo {ComputerName = item.User, CountAnswers = 1});
            var groupUsers = userInfoes.GroupBy(item => item.ComputerName, info => info.CountAnswers);
            var users = groupUsers.Select(item => new UserInfo {ComputerName = item.Key, CountAnswers = item.Sum()}).OrderByDescending(item => item.CountAnswers)
                                  .ToList();
            userRaiting.Users = users;
            userRaiting.AuthorInfo = new UserInfo
                {
                    ComputerName = GetComputerName()
                };
            var authorUser = users.FirstOrDefault(item => item.ComputerName == userRaiting.AuthorInfo.ComputerName);
            if (authorUser != null)
            {
                userRaiting.AuthorInfo.CountAnswers = authorUser.CountAnswers;
            }

            ReplaceRealNamesInUserRating(userRaiting);

            return userRaiting;
        }

        private void ReplaceRealNamesInUserRating(UserRaiting userRating)
        {
            var authorNames = ImageEntities.AuthorNames.ToList();
            var authorDictionary = authorNames.ToDictionary(item => item.ComputerName, item => item.Name);
            foreach (UserInfo user in userRating.Users.Where(item => !string.IsNullOrEmpty(item.ComputerName)))
            {
                user.Name = authorDictionary.ContainsKey(user.ComputerName)
                                ? authorDictionary[user.ComputerName]
                                : user.ComputerName;
            }

            userRating.AuthorInfo.Name = authorDictionary.ContainsKey(userRating.AuthorInfo.ComputerName)
                                             ? authorDictionary[userRating.AuthorInfo.ComputerName]
                                             : null;
        }

        public JsonResult ChangeAuthorName(string name)
        {
            lock (_lockObj)
            {
                var computerName = GetComputerName();
                var authorLink = ImageEntities.AuthorNames.FirstOrDefault(item => item.ComputerName == computerName);
                if (authorLink != null)
                {
                    authorLink.Name = name;
                }
                else
                {
                    ImageEntities.AuthorNames.Add(new AuthorName
                        {
                            ComputerName = computerName,
                            Name = name
                        });
                }

                ImageEntities.SaveChanges();

                return Json(new {correct = true});
            }
        }
    }
}

ImageEmotionalStatistics/Views/Shared/AuthorRating.cshtml
@model ImageEmotionalStatistics.Models.Shared.UserInfo

@{
    var userName = Model.Name;
    if (String.IsNullOrEmpty(userName))
    {
        userName = "Вы";
    }
}

<tr class="success">
    <td>
        <label style="display: inline;">@userName</label>
        <i class="icon-question-sign" data-toggle="tooltip" title="Вы можете изменить своё имя, кликнув на него"></i>
        <input type="hidden" value="@userName" class="inputName" data-toggle="tooltip" title="Поле сохраняется автоматически"/>
    </td>
    <td>
        @Model.CountAnswers
    </td>
</tr>

<script type="text/javascript">
    $(function() {
        $("[data-toggle='tooltip']").tooltip();
    });

    $(".success td:first-child").click(function() {
        $(this).find("label").hide().next().hide();
        $(this).find("input").attr("type", "text");
        $(this).find("input").focus();
    });
    
    $(".success input").blur(function () {
        $(this).attr("type", "hidden");
        $(this).parent().find("label").show().next().show();
        saveName($(this));
    });
    $(".success input").keydown(function (e) {
        var c = String.fromCharCode(e.keyCode);
        if (e.keyCode == 13) {
            $(this).blur();
            return;
        }
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= 'а' && c <= 'я') || (c >= 'А' && c <= 'Я')) {
            saveName($(this));
        }
    });
    
    function saveName(inputElem) {
        var val = inputElem.val();
        inputElem.parent().find("label").text(val);

        $.ajax({
            type: "POST",
            url: "@Url.Action("ChangeAuthorName", "Base")",
            data: { "name": val },
            async: false,
            success: function() {
                
            }
        });
    }
</script>

ImageEmotionalStatistics/Views/Shared/BadPage.cshtml
@{
    ViewBag.Title = "BadPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3 class="text-center">Узнай себя</h3>
    Думаю, что вы не должны были видеть эту страницу. 
    <br/>
    Попробуйте перейти обратно на <a class="link-bright" href="@Url.Action("Index", "Home")">главную страницу</a>
</div>

ImageEmotionalStatistics/Views/Shared/Raiting.cshtml
@using ImageEmotionalStatistics.Consts
@using ImageEmotionalStatistics.Models.Shared
@{
    var userRaiting = ViewData["Users"] as UserRaiting;
    string authorName = null;
    if (userRaiting != null)
    {
        authorName = String.IsNullOrEmpty(userRaiting.AuthorInfo.Name) ? userRaiting.AuthorInfo.ComputerName : userRaiting.AuthorInfo.Name;
    }
}

@if (userRaiting != null && userRaiting.AuthorInfo.CountAnswers > 0)
{
    <div id="raitingContainer">
        <div class="header">Самые активные</div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="max-width: 120px; width: 120px;">Имя <br/>активиста</th>
                    <th style="max-width: 55px; text-align: right;">Количество оценок</th>
                </tr>
            </thead>
            <tbody>
                @{
                    bool wasAuthorInTop = false;
                }
                @foreach (var user in userRaiting.Users.Take(100))
                {
                    string userName = user.Name;
                    if (userName == authorName)
                    {
                        @Html.Partial("AuthorRating", userRaiting.AuthorInfo)
                        wasAuthorInTop = true;
                    }
                    else
                    {
                        <tr>
                            <td>
                                @userName
                            </td>
                            <td>
                                @user.CountAnswers
                            </td>
                        </tr>
                    }
                }
                @if (!wasAuthorInTop)
                {
                    <tr>
                        <td>...</td>
                        <td>...</td>
                    </tr>
                    @Html.Partial("AuthorRating", userRaiting.AuthorInfo)
                }
            </tbody>
        </table>
    </div>
}

ImageEmotionalStatistics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/Script/scripts")
    </head>
    <body class="backgroundNoise">
        
        @RenderSection("ImageHelper", false)

        <div id="wrap">
            <div id="main" class="clearfix">
                <div class="absolute-Center is-Fixed">
                    @RenderBody()
                </div>
                
                @RenderSection("ImageLeft", false)
            </div>
        </div>
        
        @Html.Partial("Raiting")

        <div id="footer">
            <a href="@Url.Action("About", "Home")">Зачем это всё нужно?</a>
        </div>
    </body>
</html>